[versions]
activityCompose = "1.13.0"
agp = "9.2.1"
compose = "1.11.1"
kotlin = "2.4.0"
cortenaui = "0.3.0-alpha"
cortenaui-icons = "1.0.0"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
cortena-ui = { module = "io.github.cortenaui:ui", version.ref = "cortenaui" }
cortena-icons-phosphor = { module = "io.github.cortenaui:phosphor_icons", version.ref = "cortenaui-icons" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
